const COURSE={
meta:{title:"Mortoo Money Academy",subtitle:"Real money skills for real life"},
paths:{
  remi:{name:"Remi",age:6,color:"#FF6B35",emoji:"🦕",tagline:"Age 6 · Explorer Path",
    topics:["saving","giving","spending","entrepreneur","taxes","inflation"]},
  micah:{name:"Micah",age:8,color:"#4361EE",emoji:"🚀",tagline:"Age 8 · Champion Path",
    topics:["saving","giving","spending","entrepreneur","investing","interest","taxes","mortgage","credit","pension","inflation"]}
},
topics:{

saving:{id:"saving",title:"Saving Money",emoji:"🏦",color:"#06D6A0",
  tagline:"The habit that changes everything",
  cards:[
    {type:"story",title:"Remi's Lego Castle",icon:"🧱",
     body:"Remi spotted the most amazing LEGO castle — it cost £28! She only got £3 pocket money every week.\n\nInstead of spending it all straight away, she decided to put £2 into her special savings jar every Saturday.\n\nAfter 14 weeks... she walked into the shop and paid for it HERSELF. No asking, no waiting. Her money, her choice.\n\nThat feeling of buying something with YOUR OWN money? That's what saving gives you. 🌟"},
    {type:"concept",title:"What is a Habit?",icon:"🔄",
     body:"A habit is something you do regularly without even thinking about it — like brushing your teeth every morning.\n\nSaving is a MONEY HABIT. It means every time you get money, you put some of it away before spending anything else.\n\nAt first it feels hard. But after a few weeks, it becomes automatic — just like tying your shoelaces!\n\nThe earlier you start a good habit, the more powerful it becomes."},
    {type:"concept",title:"The 3-Jar Rule",icon:"🏺",
     body:"Here's a really simple rule:\n\n💚 SAVE jar — 50% of your money (the biggest half)\n💛 SPEND jar — 40% of your money (for fun things now)\n❤️ GIVE jar — 10% of your money (to help others)\n\nSo if you get £10:\n→ £5 goes to SAVE\n→ £4 goes to SPEND\n→ £1 goes to GIVE\n\nThis is exactly how businesses organise their money too!"},
    {type:"reallife",title:"Your Family Does This Too",icon:"🏠",
     body:"Your parents built Mortoo Homes by saving up money first, then investing it carefully.\n\nEven the most successful people in the world started as savers. Warren Buffett — one of the richest people on Earth — started saving from his paper round when he was just 13 years old.\n\nThe habit is exactly the same whether you're saving £2 a week or £2 million a month. Start small. Start NOW."},
    {type:"tip",title:"Short Goals vs Long Goals",icon:"🎯",
     body:"A SHORT goal is something you want in 1–8 weeks:\n→ A book, a game, a cool toy, a treat\n\nA LONG goal takes months to reach:\n→ A bike, a trip, a gaming console, a big LEGO set\n\nBoth need saving! The trick is to WRITE IT DOWN:\n📝 What is it?\n💰 How much does it cost?\n📅 When do you want it by?\n\nA goal without a plan is just a wish. With a plan, it becomes real!"}
  ],
  quiz:[
    {q:"Remi gets £10 pocket money. Using the 3-jar rule, how much goes in the SAVE jar?",
     options:["£1","£4","£5","£10 — save everything!"],correct:2,
     explain:"50% of £10 is £5. That's the save jar! Then £4 goes to spend and £1 goes to give."},
    {q:"What is a habit?",
     options:["Something you do once","Something you only do on weekends","Something you do regularly without thinking","Something adults do"],correct:2,
     explain:"A habit is something you do regularly — like brushing your teeth! Saving becomes a habit when you do it every single time you get money."},
    {q:"Why is it better to save BEFORE you spend, not after?",
     options:["It isn't — spend first and save the leftovers","Because if you spend first, there's often nothing left to save","Because banks close early","Saving after spending earns more interest"],correct:1,
     explain:"If you wait until after spending to save, there's usually nothing left! Save first — even just a little — and then enjoy what's remaining."}
  ],
  activity:{title:"Set Up Your 3-Jar System",
    steps:["Find 3 jars, boxes or envelopes at home",
           "Label them: SAVE 💚  SPEND 💛  GIVE ❤️",
           "Next time you get pocket money — split it straight away using the 3-jar rule",
           "Write your FIRST savings goal on a sticky note and stick it to the save jar",
           "Check your jars every week and watch that SAVE jar grow!"],
    challenge:"Can you keep the 3-jar habit going for 4 weeks without missing once?"},
  tool:{type:"savings_goal"}},

giving:{id:"giving",title:"Giving & Generosity",emoji:"❤️",color:"#FF006E",
  tagline:"The secret that makes you richer",
  cards:[
    {type:"story",title:"50p That Changed a Village",icon:"💧",
     body:"In 2022, a school in London held a fundraiser. Every child brought just 50p.\n\n400 children × 50p = £200.\n\nThat £200 was sent to Zimbabwe, where it paid to build a clean water tap used by 300 people EVERY SINGLE DAY.\n\nOne small act. Hundreds of lives changed.\n\nEvery time you put money in your GIVE jar — you have the power to do something like this. 🌍"},
    {type:"concept",title:"3 Ways to Give",icon:"🎁",
     body:"You don't need lots of money to be generous. There are 3 powerful ways to give:\n\n💰 MONEY — even 10p from your give jar makes a difference\n\n⏰ TIME — help a neighbour, tidy up without being asked, comfort a friend who's sad\n\n🛠️ SKILL — teach someone what you know. Show a friend a trick, help a younger child read\n\nAll three count equally. The most generous people give all three."},
    {type:"reallife",title:"Your Parents Give Back",icon:"🌍",
     body:"Your parents are building businesses in Africa that create jobs for hundreds of people. They could just keep all the profits.\n\nInstead they choose to build where it matters most — giving people opportunities they wouldn't otherwise have.\n\nYou don't have to choose between being generous and being successful. The very best leaders in the world are BOTH.\n\nGenerosity isn't about having lots. It's about caring enough to share what you have."},
    {type:"concept",title:"Why Generous People Thrive",icon:"🌟",
     body:"Did you know that studies show people who give regularly are:\n\n😊 Happier and less stressed\n🤝 Trusted more by other people\n💼 Often more successful in their jobs and businesses\n🌍 More connected to their community\n\nWhen you give, something magical happens — you FEEL amazing. And the people around you start to trust you and want to help you too.\n\nGenerosity isn't just nice. It's actually really SMART."}
  ],
  quiz:[
    {q:"Micah has £10. He puts £1 in his give jar. What percentage did he give?",
     options:["1%","5%","10%","50%"],correct:2,
     explain:"£1 out of £10 is 10%. That's called a 'tithe' — giving one tenth. Many generous people around the world start here."},
    {q:"Which of these counts as GIVING?",
     options:["Keeping all your pocket money","Helping a friend with their homework for free","Selling your old toys","Saving money in a jar"],correct:1,
     explain:"Giving your time and skills is just as valuable as giving money. Helping someone for free — without expecting anything back — is a true gift."},
    {q:"Why do generous people often become more successful?",
     options:["They don't — generosity makes you poorer","Giving is illegal so you avoid taxes","People trust and want to help generous people back","Charities pay you to give"]
     ,correct:2,
     explain:"When you're generous, people notice. They trust you, they like you, and they want to help YOU in return. Generosity builds incredible relationships."}
  ],
  activity:{title:"Choose Your Cause This Month",
    steps:["Look at your GIVE jar — how much is in there?",
           "Think: what's one thing in the world you'd love to help fix?",
           "Ask a parent to help you find a charity or person who works on that cause",
           "Make your first donation — however small!",
           "Write in your journal: how did it make you feel?"],
    challenge:"Give something — money, time OR skill — every single week for a whole month."},
  tool:{type:"giving_tracker"}},

spending:{id:"spending",title:"Spending Wisely",emoji:"🛒",color:"#FFD700",
  tagline:"Get more from every pound",
  cards:[
    {type:"story",title:"The Trainer Trick",icon:"👟",
     body:"Two friends both wanted new trainers.\n\nFriend A grabbed the first pair she saw — £65 — because they looked cool in the shop window.\n\nFriend B spent 20 minutes looking around. She found the same brand online in last season's colour for £29, then used a discount code for 10% off.\n\nShe paid £26.10. Both got great trainers.\n\nFriend B had £38.90 LEFT OVER for other things. Same goal. Smarter choices. 🏆"},
    {type:"concept",title:"Needs vs Wants",icon:"🤔",
     body:"A NEED is something you must have to live and function:\n→ Food, water, school supplies, shoes for school, medicine\n\nA WANT is something you'd like, but you can live without:\n→ The newest game, sweets, a toy you saw in a shop, extra gadgets\n\nBoth needs AND wants are perfectly okay!\n\nBut knowing the difference helps you decide: 'Should I buy this RIGHT NOW, or wait and think about it?'"},
    {type:"concept",title:"What is Value for Money?",icon:"⚖️",
     body:"Something is good VALUE when the quality is high for the price you pay.\n\nCheap isn't always good value.\nExpensive isn't always worth it.\n\nHere's the trick:\n\nValue = Quality ÷ Price\n\nExample: £5 socks that last 2 years = GREAT VALUE\n£1 socks that fall apart in 3 months = BAD VALUE (you'd need to buy them 8 times!)\n\nAlways ask: 'How long will this last? How much will I really use it?'"},
    {type:"tip",title:"The 3-Day Wait Rule",icon:"⏳",
     body:"Here's one of the most powerful money tricks ever:\n\nBefore buying ANYTHING over £10 — WAIT 3 DAYS.\n\n⭐ If after 3 days you still want it just as much → buy it! It's a real want.\n\n⭐ If you've kind of forgotten about it → you didn't really need it. You just had a feeling in the moment.\n\nThis one rule saves most people HUNDREDS of pounds every year. It works for adults too — your parents use this for every big business decision."},
    {type:"reallife",title:"Smart Spending in Business",icon:"💼",
     body:"When your parents considered buying a company, they didn't just pay the first price they were given.\n\nThey researched, compared, waited, and negotiated — talking the seller down to a much lower price.\n\nThat's smart spending on a MASSIVE scale. But the exact same principle works whether you're buying a game or a company:\n\n✅ Compare prices\n✅ Wait before deciding\n✅ Negotiate if you can\n✅ Ask: is this really worth it?"}
  ],
  quiz:[
    {q:"Which is a NEED and not a want?",
     options:["A new games console","The latest trainers","School lunch","A cinema trip"],correct:2,
     explain:"School lunch is something you need to function and learn every day. The others are wants — nice to have, but not essential for living."},
    {q:"A book costs £8 in one shop and £6 in another. Which is better value?",
     options:["The £8 one — it must be better quality","The £6 one","They're exactly the same","You can't tell without more information"],correct:1,
     explain:"Same book, lower price = better value. Always compare prices before you buy! A few minutes of research can save you real money."},
    {q:"What does the 3-day rule help you avoid?",
     options:["Saving too much money","Buying things on impulse that you don't really need","Forgetting to give money","Paying too much tax"],correct:1,
     explain:"The 3-day rule stops impulse buying. Most 'I MUST HAVE IT NOW!' feelings fade after a day or two. If you still want it after 3 days, then it's a real want."}
  ],
  activity:{title:"The Value Hunter Challenge",
    steps:["Pick something you want to buy this month (under £20)",
           "Find it in at least 3 different places — shops, online, second-hand markets",
           "Write down the price in each place",
           "Calculate: how much do you SAVE by choosing the cheapest option?",
           "Apply the 3-day rule before you actually buy it!"],
    challenge:"Find a way to get something you want for at least 20% less than the first price you see."},
  tool:{type:"value_compare"}},

entrepreneur:{id:"entrepreneur",title:"Entrepreneurship",emoji:"💡",color:"#8338EC",
  tagline:"Turn your ideas into income",
  cards:[
    {type:"story",title:"How Mortoo Homes Was Born",icon:"🏗️",
     body:"Your parents had a simple idea:\n\n'What if landlords never had to worry about empty properties or late rent? What if someone just guaranteed them a fixed income every month and dealt with everything?'\n\nThey solved a real problem. Landlords loved it. Mortoo Homes was born.\n\nOne idea + one problem solved = one business built.\n\nThat's ALL entrepreneurship is. You don't need to be an adult. You don't need lots of money. You just need to spot a problem and think of a solution."},
    {type:"concept",title:"The Business Formula",icon:"🧮",
     body:"Every business in the world — big or tiny — follows this same formula:\n\n🔍 SPOT a problem people have\n💡 CREATE a solution people will pay for\n📢 FIND the customers who need it\n💰 CHARGE more than it costs you to make it\n\nMoney IN (Revenue) − Money OUT (Costs) = PROFIT\n\nProfit is what you keep. Profit is freedom. Profit is what lets you save, give and invest."},
    {type:"reallife",title:"Real Kids Who Built Real Businesses",icon:"🌟",
     body:"🍋 Mikaila Ulmer — age 4 — started a lemonade stand using her great-grandmother's honey recipe. By age 14, her company 'Me & the Bees' was in thousands of shops across America.\n\n📚 Hart Main — age 13 — made scented candles for men. Made $200,000 in his first year.\n\n🍪 Cory Nieves — age 6 — sold hot chocolate and cookies. 'Mr. Cory's Cookies' is now in major stores.\n\nYou are NOT too young. You are exactly the right age to start."},
    {type:"tip",title:"Your First Business Idea",icon:"🚀",
     body:"The best first business uses what you're ALREADY good at:\n\n🎨 Love drawing? → Sell birthday cards or artwork\n📚 Great at reading? → Help younger kids with their books\n🌱 Like plants? → Grow and sell herbs or flowers\n🍰 Love baking? → Sell cookies to family friends\n🎮 Amazing at a game? → Teach others for a small fee\n\nWhat do people say you're great at? Start THERE. That's your business idea."}
  ],
  quiz:[
    {q:"Micah makes and sells 8 bookmarks for £2.50 each. Materials cost £5 total. What's his profit?",
     options:["£20","£15","£5","£25"],correct:1,
     explain:"Revenue = 8 × £2.50 = £20. Profit = £20 − £5 costs = £15. Micah made £15 from his skill and creativity!"},
    {q:"What is the MOST important thing a business needs?",
     options:["A cool logo and a website","Customers who actually pay for the product","A big office","Lots of staff from the beginning"],correct:1,
     explain:"No customers = no money = no business! Everything else (logo, office, staff) only matters AFTER you have paying customers."},
    {q:"What does Revenue − Costs = ?",
     options:["Savings","Taxes","Profit","Interest"],correct:2,
     explain:"Revenue (money in) minus Costs (money out) equals Profit — the money you actually keep! This is the most important formula in all of business."}
  ],
  activity:{title:"Launch Your First Mini-Business This Week",
    steps:["Write down 3 things you're really good at or love doing",
           "For each one, think: who would pay for this?",
           "Pick your best idea and give it a fun name",
           "Work out your price and your costs",
           "Find your first 3 customers this week!"],
    challenge:"Earn your first £5 from your own idea — then decide whether to save, give or reinvest it!"},
  tool:{type:"profit_calc"}},

investing:{id:"investing",title:"Investing & Compound Interest",emoji:"📈",color:"#059669",
  tagline:"How to turn £50/month into £500,000",
  cards:[
    {type:"story",title:"The Snowball That Became an Avalanche",icon:"⛄",
     body:"Imagine rolling a tiny snowball at the top of a very long hill.\n\nAt first it's tiny. But as it rolls, it picks up more snow. The bigger it gets, the MORE snow it picks up. By the bottom of the hill — it's enormous.\n\nThis is EXACTLY how compound interest works with money.\n\nYou start small. The growth adds to your total. Next month you earn growth on a bigger number. Then bigger again. Then BIGGER again.\n\nGive it years? It becomes life-changing. 🏔️"},
    {type:"concept",title:"Simple vs Compound Interest",icon:"🧮",
     body:"Here's the difference — and it's MASSIVE:\n\n📌 SIMPLE INTEREST:\nYou invest £1,000 at 10% per year.\nYear 1: +£100 → £1,100\nYear 2: +£100 → £1,200\nYear 3: +£100 → £1,300\nAlways the same £100.\n\n📌 COMPOUND INTEREST:\nYear 1: +£100 (10% of £1,000) → £1,100\nYear 2: +£110 (10% of £1,100) → £1,210\nYear 3: +£121 (10% of £1,210) → £1,331\n\nThe amount you earn GROWS every single year. That's the superpower."},
    {type:"concept",title:"What is the S&P 500?",icon:"🏛️",
     body:"The S&P 500 is a list of the 500 biggest companies in America — Apple, Amazon, Nike, Coca-Cola, Google, and 495 others.\n\nWhen you invest in an S&P 500 index fund, you own a tiny piece of ALL 500 companies at once.\n\nHistorically, the S&P 500 has grown at around 10% per year on average — through wars, recessions, pandemics, and crashes. It always recovered and went higher.\n\nFor a young person with decades ahead, it is one of the most proven wealth-building tools ever created. 📊"},
    {type:"reallife",title:"What £50 a Month Really Becomes",icon:"🚀",
     body:"Here's something that will blow your mind.\n\nIf Micah invests just £50 every month into an S&P 500 index fund starting RIGHT NOW:\n\n🎂 Age 18 → £7,700\n🎓 Age 25 → £26,000\n🏠 Age 35 → £114,000\n💼 Age 45 → £380,000\n🌅 Age 55 → £1,100,000\n\nThat's a millionaire — from £50 a month. The same as skipping one takeaway meal a week.\n\nThe secret? Starting EARLY and never stopping. Use the calculator to see YOUR numbers. 👇"},
    {type:"tip",title:"The Rule of 72",icon:"⚡",
     body:"Want to know how fast your money doubles? There's a brilliant shortcut called the Rule of 72.\n\n👉 Divide 72 by your annual growth rate.\n\nAt 10% growth: 72 ÷ 10 = 7.2 years to double\nAt 7% growth: 72 ÷ 7 = ~10 years to double\nAt 3% (savings account): 72 ÷ 3 = 24 years to double\n\nAt 10%, £1,000 becomes:\n→ £2,000 in 7 years\n→ £4,000 in 14 years\n→ £8,000 in 21 years\n→ £16,000 in 28 years\n\nThe S&P 500 has historically averaged close to 10%. This is why it matters so much where you put your money."}
  ],
  quiz:[
    {q:"You invest £1,000 at 10% compound interest. After Year 2, how much do you have?",
     options:["£1,200 (£100 + £100)","£1,210 (Year 2 earns £110, not £100)","£1,100","£2,000"],correct:1,
     explain:"Year 1: £1,000 + 10% = £1,100. Year 2: £1,100 + 10% = £1,210. You earn £110 in Year 2 (not £100) because compound interest grows on your TOTAL balance including previous gains!"},
    {q:"What is the S&P 500?",
     options:["A type of bank account","A list of the 500 biggest American companies you can invest in","A savings app for children","A type of mortgage"],correct:1,
     explain:"The S&P 500 tracks 500 huge companies — Apple, Amazon, Nike, Google and more. Investing in it means you own a tiny piece of ALL of them at once. Historically it's returned around 10% per year."},
    {q:"Micah invests £50/month from age 8. His twin waits until age 18. Who has more at age 65?",
     options:["They'll have exactly the same","The twin who waited — they invested harder","Micah — 10 extra years of compound growth is enormous","It depends on the stock market"],correct:2,
     explain:"Those 10 extra years are worth hundreds of thousands of pounds! Compound interest rewards patience and early starters massively. Starting at 8 vs 18 could mean the difference between £500k and over £1.5 million at age 65."}
  ],
  activity:{title:"The S&P 500 Challenge",
    steps:["Open the calculator below — set your age and monthly amount",
           "Find the amount that gets you to £500,000 by age 25 — can you do it?",
           "Now try: what monthly amount makes you a millionaire by age 55?",
           "Ask a parent to search 'Vanguard S&P 500 Junior ISA' — this is a real account you can open",
           "Write down your investing goal: £___ per month from age ___ to reach £___ by age ___"],
    challenge:"Get your parents to open a real Junior Stocks & Shares ISA this month — start with whatever you can afford, even £10."},
  tool:{type:"sp500_calc"}},

interest:{id:"interest",title:"Interest & APR",emoji:"💳",color:"#DC2626",
  tagline:"Why borrowing money costs extra",
  cards:[
    {type:"story",title:"The Sibling Loan",icon:"💸",
     body:"Micah lent Remi £10 to buy an art kit. He said: 'Pay me back £11 next month.'\n\nThat extra £1 is INTEREST — Micah's reward for letting Remi use his money.\n\nNow imagine borrowing £1,000 from a bank at 20% APR. After one year you owe £1,200.\n\nBorrow on a credit card and only pay the minimum each month? It could take 10 years to clear and cost you over £3,000 total.\n\nThe cost of borrowing is REAL. Always know what you're signing up for."},
    {type:"concept",title:"What is APR?",icon:"📊",
     body:"APR = Annual Percentage Rate\n\nIt tells you the YEARLY cost of borrowing money, shown as a percentage.\n\n✅ Bank loan: 5–8% APR (relatively affordable)\n⚠️ Car finance: 10–15% APR\n🔴 Credit card: 20–30% APR\n🚨 Payday loan: 1,000–3,000% APR (extremely dangerous)\n\nThe LOWER the APR, the cheaper the borrowing.\n\nAlways ask: 'What's the APR?' before agreeing to any loan."},
    {type:"tip",title:"Good Debt vs Bad Debt",icon:"⚖️",
     body:"Not all borrowing is bad!\n\nGOOD DEBT — borrowing to CREATE more money:\n✅ Mortgage — to own a home that grows in value\n✅ Business loan — to start something profitable\n\nBAD DEBT — borrowing to CONSUME:\n❌ Credit card for holidays you can't afford\n❌ Loans for clothes, gadgets or impulse buys\n❌ 'Buy now pay later' for things you don't need\n\nYour parents use business loans strategically — always with a clear plan to repay from profits."}
  ],
  quiz:[
    {q:"You borrow £500 at 20% APR. How much interest do you pay in 1 year?",
     options:["£20","£50","£100","£500"],correct:2,
     explain:"20% of £500 = £100 in interest. So you'd repay £600 total. That's the real cost of borrowing — you always pay back more than you borrowed."},
    {q:"Which loan is CHEAPER to borrow?",
     options:["5% APR","20% APR","50% APR","They all cost the same"],correct:0,
     explain:"Lower APR = less interest = cheaper loan. Always choose the lowest APR available when you need to borrow. Even a few percent difference adds up to hundreds of pounds over time."},
    {q:"Which is an example of GOOD debt?",
     options:["Credit card for a luxury holiday","Loan for new trainers","A mortgage to buy a house","Buy now pay later for a games console"],correct:2,
     explain:"A mortgage is good debt because you're building an asset — a home — that can grow in value over time. The property itself is working for you."}
  ],
  activity:{title:"The APR Comparison Mission",
    steps:["Look up 3 different ways to borrow £1,000 (bank loan, credit card, overdraft)",
           "Find the APR for each one",
           "Use the calculator to see how much each costs in 1 year",
           "Write down the difference in cost between the cheapest and the most expensive",
           "Ask your parents: what APR would they consider acceptable for a business loan?"],
    challenge:"Find a real credit card offer online. Calculate exactly how much £500 borrowed would cost over 1 year."},
  tool:{type:"apr_calc"}},

taxes:{id:"taxes",title:"Understanding Taxes",emoji:"🏛️",color:"#0284C7",
  tagline:"The money we share to build our world",
  cards:[
    {type:"story",title:"The Class Pot",icon:"🏫",
     body:"Imagine 30 children each put 10p into a class pot every day at school.\n\nThat's £3 per day. In a school year (190 days) = £570!\n\nWith that money, the class buys books, art supplies, a projector, and fixes a broken shelf. None of them could afford all of that on their own.\n\nBut TOGETHER, they built something extraordinary.\n\nThat's exactly what taxes do — on a national scale, for millions of people."},
    {type:"concept",title:"Types of Tax",icon:"📋",
     body:"💼 INCOME TAX — paid on what you earn from a job. UK basic rate = 20%.\n\n🛒 VAT (Value Added Tax) — 20% added to most things you buy. It's already included in the price.\n\n🏢 CORPORATION TAX — paid by businesses on their profits.\n\n🏠 STAMP DUTY — a tax paid when buying property.\n\nTaxes fund things that everyone uses together — schools, hospitals, roads, emergency services."},
    {type:"reallife",title:"What Your Taxes Build",icon:"🌐",
     body:"Every time you buy something, 20p in every £1 goes to the government as VAT. That money pays for:\n\n🏥 The NHS — doctors, hospitals, ambulances\n🚓 Police and fire services\n🛣️ Roads, bridges and public transport\n📚 Schools and libraries\n🌳 Parks and public spaces\n\nYour parents have an accountant whose whole job is making sure every tax is calculated correctly and paid on time — not too much, not too little."}
  ],
  quiz:[
    {q:"What is VAT?",
     options:["A type of savings account","A 20% tax added to most things you buy","The money you earn from a job","A special bank for businesses"],correct:1,
     explain:"VAT stands for Value Added Tax — 20% added to most things you buy. It's already included in the price you see. The shop collects it and passes it to the government."},
    {q:"A toy costs £12 including 20% VAT. How much of that is tax?",
     options:["£2.40","£2","£1.20","£0.20"],correct:1,
     explain:"If the total price including 20% VAT is £12, the original price was £10, and the VAT = £2. That £2 goes straight to the government to fund public services."},
    {q:"Name TWO things paid for by taxes.",
     options:["Private schools and luxury cars","Profit and revenue","Schools and hospitals","Pocket money and savings"],correct:2,
     explain:"Schools and hospitals are funded by taxes! So are roads, police, fire services, parks and libraries. Every time you use these, you're benefiting from taxes."}
  ],
  activity:{title:"Tax Detective Mission",
    steps:["Next time you're at a shop — find the VAT line on the receipt",
           "Calculate what percentage of the total bill is tax",
           "Find out: what 3 things near your home were built or funded by taxes?",
           "Make a list of 10 things in your everyday life that taxes pay for",
           "Ask your parents: how do they make sure they pay the right amount of tax?"],
    challenge:"Create a 'tax budget' — if YOU had £100 of tax money to spend, how would you divide it?"},
  tool:{type:"tax_calc"}},

mortgage:{id:"mortgage",title:"Mortgages",emoji:"🏠",color:"#0369A1",
  tagline:"How families buy homes with long-term loans",
  cards:[
    {type:"story",title:"The Mortoo Connection",icon:"🔑",
     body:"Every property Mortoo Homes manages was bought by someone using a mortgage.\n\nA landlord might have bought a flat for £250,000, saved a £50,000 deposit, and borrowed £200,000 from the bank.\n\nYour parents collect rent from tenants, pay the landlord a guaranteed income, and the landlord uses some of that to pay their mortgage.\n\nYour parents designed this whole system. Understanding mortgages is at the very heart of it."},
    {type:"concept",title:"How a Mortgage Works",icon:"🏗️",
     body:"Step 1: You find a house — say it costs £300,000\nStep 2: You save a DEPOSIT — usually 10–20% (£30,000–£60,000)\nStep 3: The bank lends you the REST (£240,000–£270,000)\nStep 4: You pay back monthly — part pays off the loan, part is interest\nStep 5: After 25 years — the house is YOURS, and it's worth far more than you paid\n\nYou're essentially 'renting' from the bank — but at the end, you OWN the house completely."},
    {type:"tip",title:"Fixed vs Variable Rate",icon:"📌",
     body:"FIXED RATE: Your monthly payment stays exactly the same for 2–5 years.\n→ Easier to budget. Safe when rates might go up.\n\nVARIABLE RATE: Moves up or down with the Bank of England's base rate.\n→ Can go up OR down. Sometimes cheaper, but more risky.\n\nYour parents think very carefully about interest rates on every property deal. When rates go up, mortgages become more expensive — which affects landlords, which affects Mortoo Homes too. Everything is connected."}
  ],
  quiz:[
    {q:"A house costs £200,000. You put down a 10% deposit. How much do you borrow?",
     options:["£200,000","£20,000","£180,000","£100,000"],correct:2,
     explain:"10% of £200,000 = £20,000 deposit. You borrow the remaining £180,000 from the bank. That £180,000 is your mortgage."},
    {q:"What happens at the END of a mortgage term?",
     options:["You have to sell the house","You owe the bank nothing and fully own the house","You start a new mortgage","The bank keeps the house"],correct:1,
     explain:"Once all monthly payments are made, your mortgage is cleared! The house is 100% yours with no more payments to the bank. And it's usually worth much more than you paid!"},
    {q:"Why is a BIGGER deposit usually better?",
     options:["It isn't — smaller deposits are smarter","You borrow less so you pay much less interest over 25 years","Banks give cash gifts for big deposits","It improves your credit score instantly"],correct:1,
     explain:"Bigger deposit = smaller loan = less interest over 25 years. Saving a larger deposit before buying can save you tens of thousands of pounds total."}
  ],
  activity:{title:"Design Your Dream Home Budget",
    steps:["Find a real home you'd love to own one day — search Rightmove or Zoopla",
           "Note the price. Calculate both a 10% and a 20% deposit",
           "Use the mortgage calculator to see the monthly payments for each",
           "Work out: how many years would you need to save the deposit, saving £500/month?",
           "Ask your parents: how did the landlords they work with buy their first property?"],
    challenge:"Use the calculator to find: what monthly payment could you afford if you earned £3,000 a month?"},
  tool:{type:"mortgage_calc"}},

credit:{id:"credit",title:"Credit Score",emoji:"⭐",color:"#7C3AED",
  tagline:"Your financial reputation — build it early",
  cards:[
    {type:"story",title:"The Reputation Report",icon:"📋",
     body:"Imagine a new student arrives at your school. Nobody knows them yet.\n\nSix months later, every teacher says: 'Always honest, always on time, always keeps promises.'\n\nIf that student asks to borrow the school equipment, teachers say YES immediately and offer the BEST stuff.\n\nA credit score is your FINANCIAL reputation report. Banks check it before lending money. Higher score = better deals, bigger loans, more trust. Lower score = rejection, sky-high rates, very limited options."},
    {type:"concept",title:"The Credit Score Scale",icon:"📊",
     body:"In the UK (Experian), scores run from 0 to 999:\n\n⭐⭐⭐⭐⭐ 961–999: Excellent — best possible rates\n⭐⭐⭐⭐ 881–960: Good — competitive rates\n⭐⭐⭐ 721–880: Fair — average rates\n⭐⭐ 561–720: Poor — higher rates\n⭐ 0–560: Very Poor — likely rejected\n\nA great credit score saves you thousands on mortgages and loans over your lifetime. Your score follows you your whole adult life."},
    {type:"tip",title:"Build a Great Credit Score",icon:"🏆",
     body:"These things HELP your score:\n✅ Pay every single bill on time — always\n✅ Register on the electoral roll when you're 18\n✅ Keep old accounts open (history matters)\n✅ Don't use more than 30% of your credit limit\n\nThese things HURT your score:\n❌ Missing payments\n❌ Applying for lots of credit at once\n❌ Going over your credit limit\n❌ Ignoring bills\n\nYour adult financial life begins at 18. Protect your reputation from day one."}
  ],
  quiz:[
    {q:"Which action MOST helps your credit score?",
     options:["Applying for 5 credit cards at once","Paying every single bill on time for 2 years","Spending right up to your credit limit every month","Closing all your old accounts"],correct:1,
     explain:"Consistent on-time payments over time is the #1 way to build credit. Lenders want proof you're reliable. Two years of perfect payments sends a very powerful signal."},
    {q:"Why does a better credit score save you money?",
     options:["Banks give you cashback rewards","You get lower interest rates on mortgages and loans","You pay less VAT on purchases","Your insurance gets cheaper"],correct:1,
     explain:"A great credit score = lower APR on your mortgage. Over 25 years, a 1% difference in mortgage rate can save you TENS of thousands of pounds. Your credit score is incredibly valuable."},
    {q:"Micah turns 18. What's his FIRST step to building great credit?",
     options:["Apply for a £10,000 loan","Register on the electoral roll and open a bank account","Apply for 3 credit cards at once","Take out a payday loan"],correct:1,
     explain:"Electoral roll registration and a bank account are the foundation. They prove your identity and address to lenders and start your credit history."}
  ],
  activity:{title:"The Trust Tracker Journal",
    steps:["Get a notebook — call it your 'Financial Reputation Journal'",
           "Every time you keep a money promise (pay someone back, save what you said you would) → green tick ✓",
           "Every miss → red cross ✗",
           "At the end of each month, count your ratio",
           "Goal: 100% green ticks every month. That's an Excellent credit score in real life."],
    challenge:"Go 30 days without a single broken money promise. Perfect score!"},
  tool:{type:"credit_simulator"}},

pension:{id:"pension",title:"Pension",emoji:"🌅",color:"#D97706",
  tagline:"Plant now. Harvest for life.",
  cards:[
    {type:"story",title:"The Two Brothers",icon:"⏰",
     body:"Two brothers, Kwame and Kofi.\n\nKwame starts putting £200 a month into his pension at age 20. He stops at 40 — 20 years of saving (£48,000 total).\n\nKofi waits until age 40, then saves £200/month until 65 — 25 years (£60,000 total).\n\nAt age 65:\nKwame: £682,000 🏆\nKofi: £304,000\n\nKwame invested LESS money but started EARLIER. Time is the most powerful force in personal finance. Start early. Always."},
    {type:"concept",title:"What is a Pension?",icon:"🏦",
     body:"A pension is a special savings account you can't touch until retirement (around age 57–67).\n\nIn exchange for that patience, you get incredible benefits:\n\n🎁 Government adds 25% tax relief — put in £100 and it's worth £125 INSTANTLY\n🎁 Employers often add extra contributions — free money!\n🎁 Grows completely tax-free for decades\n\nA good pension can replace your salary for 20–30 years of retirement. The UK state pension alone (~£221/week) is nowhere near enough to live on comfortably."},
    {type:"reallife",title:"The Entrepreneurial Pension",icon:"🏢",
     body:"Your parents are building businesses partly as their 'pension' — companies that generate ongoing income and can be sold for large sums later.\n\nThis is the entrepreneurial approach: own assets that pay YOU.\n\nBut even entrepreneurs usually have a pension too — for the tax advantages and as a safety net.\n\nThe lesson? Build businesses AND save for retirement. Both. Not one or the other."}
  ],
  quiz:[
    {q:"Why does starting a pension at 20 beat starting at 40?",
     options:["The government gives more relief to young people","More years for compound growth to work","Inflation doesn't affect young people's savings","Employers match more when you're young"],correct:1,
     explain:"Time is your greatest asset. 40 years of compound growth massively outperforms 25 years — even with more total money invested. Starting early is everything."},
    {q:"You put £100 into your pension. With 25% tax relief, how much is in your pension?",
     options:["£100","£120","£125","£150"],correct:2,
     explain:"The government adds 25% tax relief, so £100 becomes £125 instantly. That's a 25% return before any investment growth — better than almost any investment!"},
    {q:"What's the risk of relying ONLY on the UK state pension?",
     options:["It's illegal to rely on it","At around £221 per week, it's not enough to live comfortably","You have to reapply every year","It gets taxed at 50%"],correct:1,
     explain:"The UK state pension is about £11,500 per year. That's very limited for a comfortable retirement. A private pension gives you freedom, choice and security."}
  ],
  activity:{title:"Design Your Dream Retirement",
    steps:["Imagine your perfect life at age 65 — write it down in detail",
           "Estimate how much that life would cost per month",
           "Use the pension calculator to see what monthly savings get you there",
           "Ask your parents how they think about retirement through their businesses",
           "Decide: what age do YOU want to be financially free by?"],
    challenge:"Ask a parent to open a Junior SIPP (pension) in your name — start with just £10."},
  tool:{type:"pension_calc"}},

inflation:{id:"inflation",title:"Inflation",emoji:"🎈",color:"#DC2626",
  tagline:"Why £1 today buys more than £1 tomorrow",
  cards:[
    {type:"story",title:"The Sweet Shop Time Machine",icon:"🍫",
     body:"Ask any grandparent: 'What did sweets cost when you were my age?'\n\nIn 1970 a chocolate bar cost about 3p.\nIn 1990 it was around 25p.\nToday it's around £1.20.\n\nThe chocolate didn't change. The money changed.\n\nEvery year, most things get slightly more expensive. This is INFLATION — and it's why hiding £100 in a piggy bank is quietly losing you money every single year, even while it sits still."},
    {type:"concept",title:"How Inflation Works",icon:"📉",
     body:"When there's more money chasing the same amount of goods, prices go up.\n\nIf inflation = 3% per year:\n→ £100 today buys what £97 buys next year\n→ £100 today buys what £74 buys in 10 years\n→ £100 today buys only what £41 buys in 30 years\n\nYour money LOSES purchasing power just by sitting still.\n\nThe Bank of England tries to keep inflation at exactly 2% per year. When it rises, they increase interest rates to slow it down. This affects EVERY mortgage and loan in the country."},
    {type:"reallife",title:"Property Beats Inflation",icon:"📰",
     body:"Your parents' property business is a natural inflation SHIELD.\n\nWhen inflation rises, house prices and rents usually rise too — which means the properties are worth more AND generate more income.\n\nThat's one reason property is such a powerful investment — it tends to hold and grow its real value even when inflation is high.\n\nThis is why simply earning money isn't enough. You need to INVEST it in things that grow faster than inflation."},
    {type:"tip",title:"Beat Inflation",icon:"🏆",
     body:"Losing to inflation: money in a piggy bank (0% growth vs 3% inflation = −3% real loss every year)\n\nJust keeping up: savings account at 3% = breaking even (not losing but not gaining)\n\nBeating inflation: investing in stocks, property or businesses → historically 7–10% per year\n\nThe goal isn't just to GROW your money. It's to grow it FASTER than inflation.\n\nReal Return = Your Growth % − Inflation %"}
  ],
  quiz:[
    {q:"If inflation is 4% and your savings account pays 2%, what is your real return?",
     options:["+2% — you're growing","+6% — they add together","-2% — you're losing purchasing power","0% — they cancel out perfectly"],correct:2,
     explain:"Real return = growth rate minus inflation. 2% − 4% = −2%. Your money feels the same but buys LESS every year. You need to beat inflation, not just match it."},
    {q:"A chocolate bar costs £1 today. With 5% annual inflation, what will it cost in 10 years?",
     options:["£1.50","£1.63","£2.00","£1.05"],correct:1,
     explain:"£1 × 1.05^10 = £1.63. Compound inflation builds up just like compound interest — slowly at first, then faster and faster."},
    {q:"Why is property often called an 'inflation hedge'?",
     options:["Property never ever loses value","Property prices and rents tend to rise WITH inflation","You don't pay VAT on houses","The government protects all property prices"],correct:1,
     explain:"As inflation rises, building costs and land values rise too — which means property values tend to keep pace with or even beat inflation over time. It protects your wealth."}
  ],
  activity:{title:"The Inflation Time Machine",
    steps:["Ask a grandparent or older relative: what did 5 everyday things cost in their childhood?",
           "Look up what those same 5 things cost today",
           "Calculate the % increase for each one",
           "Use the inflation calculator to find what the annual inflation rate must have been",
           "Compare to the official UK inflation rate — how close were they?"],
    challenge:"Find one investment that has beaten inflation in EVERY decade since 1970."},
  tool:{type:"inflation_calc"}}

}};
